### PR TITLE
Bump select

### PR DESCRIPTION
**Pull request by erlingfn**
Bump react-select a lot of versions :sweat:

### CODE REVIEW

**Review by LudvigHz — APPROVED** [review]
Oh damn. Hope this works :upside_down_face:.
Otherwise LGTM

**Review by AdrianAndersen — APPROVED** [review]

**Comment by SmithPeder** [comment]
@erlingfn 
Was this done?

**Comment by AdrianAndersen** [comment]
> @erlingfn
> Was this done?

I thought Erling said it was done at our meeting yesterday, but I might be mistaken. The code looked good tho.

**Comment by SmithPeder** [comment]
Nice! Yeah, I was not at the meeting so I don't know :D Then it's probably good

**Pull request merged**
