### PR TITLE
Fix paging and members table becoming empty

### PR DESCRIPTION
**Pull request by Bestem0r**
# Description

Previously the pagination on the group members page was not working. This would also cause the members table to become empty when editing roles. 

Changes:
- Fixed paging on the group members table
- Fixed group members table becoming empty when editing user roles 

# Result

Previously:
[Screencast from 20. feb. 2024 kl. 13.18 +0100.webm](https://github.com/webkom/lego-webapp/assets/33326578/96dc148f-73be-4cb6-bdcc-1a3f8a61a9b5)

Fixed:
[Screencast from 20. feb. 2024 kl. 13.39 +0100.webm](https://github.com/webkom/lego-webapp/assets/33326578/804d8ade-44c3-4c5b-927d-f5bfa84957c1)

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

# Testing

- [x] I have thoroughly tested my changes.

- Navigate to `/admin/groups/11/members`
- Change the role of one of the members.
- Verify that the table does not become empty and that the role is correctly updated.
- Navigate to `/admin/groups/3/members`.
- Scroll down and verify that paging works.

Resolves ABA-793

### CODE REVIEW

**Review by haukkagu — APPROVED** [review]
Works on my machine. Good job!

**Review by itsisak — APPROVED** [review]
Nice! Just curious; would it be possible to prevent the table from disappearing while it fetches after role is updated? It would be a bit more smuud, but I get if this would be tricky

**Review by magnusbrecke — APPROVED** [review]
Looks good to me. Good code

**Review by norbye — APPROVED** [review]
Good job!

Now that this works again, it might be worth testing if the changes made in https://github.com/webkom/lego-webapp/pull/4412 to solve the clearing of the table upon editing roles are really necessary:) if they aren't it would be sweet to not fetch the entire list manually after submitting

**Review by dobif — APPROVED** [review]
Works for me. Does the page need to load the entire table after updating the roles?

**Pull request merged**
