### PR TITLE
Frontpage

### PR DESCRIPTION
**Pull request by SmithPeder**
What do people think, any suggestions?

screenshot from 2018-09-23 02-14-25

### CODE REVIEW

**Comment by edvardvb** [comment]
Pretty! Kind of reminds me of the old frontpage from NERD 😏

I'd love to have separate lists for articles and events, but not sure how to find the space for that

**Comment by SmithPeder** [comment]
Ohh :/  I don't remember much of how NERD looked. But yeahh a separate list for articles is a great idé. Let me change some stuff.

**Comment by edvardvb** [comment]
While we're at it, let's rework the entire "pinned"-system

Currently 3-4 articles or events are pinned at all times, making the system kinda flawed. Even though that's not how we wanted it to be used, it's kind of evident that we need something that actually covers our users' needs.

**Comment by odinuge** [comment]
@JonasBak :arrow_up:

**Comment by SmithPeder** [comment]
Yehh, the pinned system is kinda flawed. @JonasBak has made a "slide-show" version of the pinned element. It can also show elements that are pinned for groups you're in. Like HÆLGA and KICKSTART and so forth.

**Comment by SmithPeder** [comment]
@edvardvb  What do you think about this list separating scheme?

screenshot from 2018-09-23 18-32-19

**Comment by SmithPeder** [comment]
**Issues:**

- [ ] What the hell should this look like on a phone
- [ ] Change the backend `FrontpageViewSet` view to use include the `PoolReadSerializer` when getting events, so I can access the `activation_date` field

**Comment by SmithPeder** [comment]
screenshot from 2018-10-07 19-22-18

screenshot from 2018-10-07 19-38-23

screenshot from 2018-10-07 19-56-53

**Pull request merged**
