### PR TITLE
Add support for filtering on date published

### PR DESCRIPTION
**Pull request by odinuge**
Should we use `createdAt` as default instead of the current `deadline`?

### CODE REVIEW

**Comment by SmithPeder** [comment]
> Should we use createdAt as default instead of the current deadline?

Hmm, I see how it could be nice to have `createdAt` as the default, but I feel like it's more natural to have `deadline`. Getting a listing that was just created but has a deadline on 1.mai at the top is kinda strange.

**Comment by odinuge** [comment]
> Hmm, I see how it could be nice to have createdAt as the default, but I feel like it's more natural to have deadline. Getting a listing that was just created but has a deadline on 1.mai at the top is kinda strange.

Yeah, fair point. But then it is easier to spot new stuff tho., but it definitely a tradeoff. Guess we can use the users grade to show most relevant stuff on top as well

**Comment by liseph** [comment]
I agree with Peder, `deadline` feels more natural. We could consider pinning new ones at the top, but that would either have to be static, like pinned for 24h, or dynamic for each user (new for you). I suppose the last option is better, but that would require some more work...  :no_good:

**Review by liseph — APPROVED** [review]
lgtm :woman_shrugging:

**Pull request merged**
