### PR TITLE
zxcvbn password validation

### PR DESCRIPTION
**Pull request by liseph**
## “Slow progress is better than no progress.”
Implement ZXCVBN password validator from Dropbox
https://github.com/dropbox/zxcvbn
https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/

Missing: Get user data to validator for reset password. Decided this is ok.

I also added confirm password fields to create user and reset password. 

Create user:
Screenshot from 2019-03-26 16-46-58

Reset password:
Screenshot from 2019-03-26 16-42-26

Change password:
Screenshot from 2019-03-26 16-48-47

### CODE REVIEW

**Comment by SmithPeder** [comment]
@liseph This still WIP?

**Comment by liseph** [comment]
@SmithPeder Yup
Missing: Get user data to validator for change and reset password.
Will probably not fix this before the summer, but probably after the exams (end of may).

**Comment by SmithPeder** [comment]
> Will probably not fix this before the summer, but probably after the exams (end of may).

**Review by odinuge — APPROVED** [review]
lgtm

Awesome!! 🙌🙌

**Pull request merged**
