### PR TITLE
Don't push route on modal

### PR DESCRIPTION
**Pull request by SmithPeder**

### CODE REVIEW

**Review by LudvigHz — APPROVED** [review]
Hmm, weird how this got in here :thinking:

**Comment by SmithPeder** [comment]
I got a theory, maybe they stole it from here :D So I guess you can't delete Companies in the `BDB` either 🙃 
https://github.com/webkom/lego-webapp/blob/c87589654355bd0fe85bcadaa2287b8b540e94a7/app/routes/bdb/utils.js#L185-L193

**Comment by SmithPeder** [comment]
@LudvigHz One could not delete companies either, so this fixes this as well. looked at all the other `ConfirmModalWithParant` and these two were the only ones that used the `NavigationLink`

**Comment by LudvigHz** [comment]
Nice :ok_hand:

**Comment by erlingfn** [comment]
Great work!

**Pull request merged**
