### PR TITLE
Add readme-as-a-function

### PR DESCRIPTION
**Pull request by odinuge**

### CODE REVIEW

**Comment by SmithPeder** [comment]
Nothing's like implementing a little GraphQL into the stack :100:

**Comment by odinuge** [comment]
10/10 må ha

**Comment by SmithPeder** [comment]
Dam you changed `Overview.js`, now i have to rebase the frontpage pull request :-1:  0/10

**Comment by odinuge** [comment]
Ahaha, glemte det helt! Fiks sånn at testene på den passer, sånn at vi kan merge den, så må jeg rebase istede :smile:

**Comment by SmithPeder** [comment]
What's all this Norwegian talking, are we switching to the native language of our people?

**Comment by odinuge** [comment]
Hola amigo. :1234: 

No comprendo :confused:

**Comment by SmithPeder** [comment]
And the `frontpage` will pass the test if I remove the `console.log()` _whom I left on purpose_. There are still two large issues left there so you can go ahead and merge this first.
Then I can practise merging things with conflicts.

**Pull request merged**
