### PR TITLE
Add some cool beachy features for the sommerfest

### PR DESCRIPTION
**Pull request by jennymul**
# Description

Add some waves, surfboards and some margaritas :))

# Result

- [X] Changes look good on both light and dark theme.
- [ ] Changes look good with different viewports (mobile, tablet, etc.).
- [X] Changes look good with slower Internet connections.

> [!CAUTION]
> Make sure your images do not contain any real user information.

# Testing

- [X] I have thoroughly tested my changes.

---

### CODE REVIEW

**Review by ShaileshS1702 — APPROVED** [review]
LGTM!
Nice with some new summer-themed feature

**Review by AdrianAndersen — APPROVED** [review]
🤫

**Review by ShaileshS1702 — APPROVED** [review]
LGTM!

**Review by ivarnakken — APPROVED** [review]
LGTM😋

**Review by itsisak — APPROVED** [review]
Great work!

**Comment by magnusbrecke** [comment]
LGTM!

**Pull request closed without merging**
