### PR TITLE
La til en tidtaker på Abakus.no

### PR DESCRIPTION
**Pull request by ShaileshS1702**
# Description

La til en nedtelling i banner på abakus.no

# Result

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [ ] Changes look good with slower Internet connections.

> [!CAUTION]
> Make sure your images do not contain any real user information.

<table>
    <tr>
        <td width="25%">Description</td>
        <td>Before</td>
        <td>After</td>
    </tr>
    <tr>
        <td>
        </td>
        <td>
image
        </td>
        <td>
image
        </td>
    </tr>
    <tr>
        <td>
        </td>
        <td>
        </td>
        <td>
image
        </td>
</tr>
</table>

# Testing

- [x] I have thoroughly tested my changes.

Please describe what and how the changes have been tested, and provide instructions to reproduce if necessary.

---

Resolves ... (either GitHub issue or Linear task)

### CODE REVIEW

**Review by falbru — APPROVED** [review]
This works on my machine, although I think something like this would be cleaner: https://www.geeksforgeeks.org/how-to-use-setinterval-method-inside-react-components/

**Review by norbye — COMMENTED** [review]
I'd preferably have this logic contained within the banner component - as it is not needed for anything else on the frontpage. If you only want this to happen for authenticated users it's simple enough to fetch `const { loggedIn } = useUserContext();` within the Banner component.

Throwing in a ➕1 on @falbru's comment. If you want a live example of it we currently use it in admissions https://github.com/webkom/admissions/blob/master/frontend/src/routes/LandingPage/CountDown.tsx

**Comment by ShaileshS1702** [comment]
I didn't have enough time to look at it today. I will try to look at a solution tomorrow

**Comment by ShaileshS1702** [comment]
> I'd preferably have this logic contained within the banner component - as it is not needed for anything else on the frontpage. If you only want this to happen for authenticated users it's simple enough to fetch `const { loggedIn } = useUserContext();` within the Banner component.
> 
> Throwing in a ➕1 on @falbru's comment. If you want a live example of it we currently use it in admissions https://github.com/webkom/admissions/blob/master/frontend/src/routes/LandingPage/CountDown.tsx

Isn't the AuthenticatedFrontpage only available for those who has loggedIn, or should I do a check on that?

**Comment by norbye** [comment]
> Isn't the AuthenticatedFrontpage only available for those who has loggedIn, or should I do a check on that?

Yes it is, and if this is only a temporary one off thing there's no need to do it and you won't add the banner on the non-authenticated front page - I was just thinking more permanent

**Pull request closed without merging**
