### PR TITLE
Refactor and clean up achievements on user profile

### PR DESCRIPTION
**Pull request by ivarnakken**
# Description

*Cleaner and less custom styling
*Resembles the other content more
*No more card
*No more console warning
*Fix text shadow on name
*More responsive on different viewports
*No overflow on mobile
*No magic numbers
*Improved naming

# Result

- [x] Changes look good on both light and dark theme.
- [ah yes] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

<table>
    <tr>
        <td>Before</td>
        <td>After</td>
    </tr>
    <tr>
        <td>
            image
        </td>
        <td>
            image
        </td>
    </tr>
    <tr>
        <td>
            image
        </td>
        <td>
            image
        </td>
    </tr>
</table>

# Testing

- [x] I have thoroughly tested my changes.

Tested on pretty much all viewports (see images above).

### CODE REVIEW

**Comment by jonasdeluna** [comment]
Is it just me or does the after one look a bit off-center on desktop?

**Comment by ivarnakken** [comment]
>  Is it just me or does the after one look a bit off-center on desktop?

Yes, that is very much intentional. No other content on the page is centered so it looks off imo - better to be consistent with the events, the membership pills and bages, and user infos.

On smaller viewports it is centered though, like the other content.

**Review by jonasdeluna — APPROVED** [review]
Looks nice, but one of the innermost divs should probably have a different justify-content value?

**Comment by jonasdeluna** [comment]
> > Is it just me or does the after one look a bit off-center on desktop?
> 
> Yes, that is very much intentional. No other content on the page is centered so it looks off imo - better to be consistent with the events, the membership pills and bages, and user infos.
> 
> On smaller viewports it is centered though, like the other content.

Hmm I see. Compared to the groups though, it is much clearer what the border is so it looks "worse" even though they are both left-centered imo.

**Comment by ivarnakken** [comment]
> but one of the innermost divs should probably have a different justify-content value?

Not sure what you're referencing here hehe

**Comment by jonasdeluna** [comment]
Oops reviewed it before I read your reply comment

**Comment by ivarnakken** [comment]
> Hmm I see. Compared to the groups though, it is much clearer what the border is so it looks "worse" even though they are both left-centered imo.

hmm perhaps

Imo I don't see why this needs to be in a card at all 🤷🏼‍♂️

**Comment by eikhr** [comment]
I think it looks a bit weird to have them uncentered inside the card, I vote that we remove the card.

**Review by eikhr — APPROVED** [review]

**Comment by ivarnakken** [comment]
Removed the card - think it looks better:
image

**Comment by ivarnakken** [comment]
I "accidentally" fixed this shadow when fixing a console error about an unwanted semicolon - is this shadow feature still wanted?

image

In my opinion it's cool, but the shadow should be the same color as the trophy, or?

**Comment by ivarnakken** [comment]
@eikhr your page looks a bit cooler than mine
image

**Comment by jonasdeluna** [comment]
This looks great!

**Pull request merged**
