### PR TITLE
Improve button class design

### PR DESCRIPTION
**Pull request by AdrianAndersen**
The current button design is quite poor. It needs more difference between the disabled and clickable button. (Especially in dark mode) Therefore, I suggest making the following changes.

Feel free to suggest changes to the colours / shadows etc! 🧑‍🎨 

#### Before / After
imageimage 

#### Before / After
imageimage

### CODE REVIEW

**Review by ivarnakken — APPROVED** [review]
Nice! I've wanted to change up our buttons for so long!😍

**Review by LudvigHz — COMMENTED** [review]
Nice! I definitely agree our buttons don't look the best.

Although I strongly suggest **not** using red as a main button color, as we use that for all delete and danger buttons.

**Comment by AdrianAndersen** [comment]
> 

Yeah, it resembles that. However I think it is fine since it matches our theme. We could do something about our critical buttons. For instance having an icon, or a “danger zone” like GitHub. What do you think, @LudvigHz?

**Comment by LudvigHz** [comment]
> > 
> 
> Yeah, it resembles that. However I think it is fine since it matches our theme. We could do something about our critical buttons. For instance having an icon, or a “danger zone” like GitHub. What do you think, @LudvigHz? Or do you have a suggestion for another good color?

I think that red buttons are so unanimously used as a "danger" button across the web that it doesn't matter if it matches our primary color. I think it's a bad idea (tbh my brain hurts when looking at the pool example :upside_down_face:). So for how they should look I'm not too sure, maybe a white/gray button with some border or something? Or we could use another color in our palette (or add one?)

**Pull request merged**
