### PR TITLE
Refactor DatePicker- and TimePicker-component

### PR DESCRIPTION
**Pull request by eikhr**
# Description

Small refactor of the DatePicker thingy. Shouldn't change too much, but rewrote to functional components and simplified the logic a bit. ~100 fewer lines of code:)

# Result

Some minor changes in appearance:

<table>
<tr>
 <td>Before</td>
 <td>After</td>
<tr>
 <td>Screenshot 2023-05-27 at 18 54 41</td>
 <td>Screenshot 2023-06-10 at 10 25 07</td>
</table>

~~I have changed the behaviour slightly to simplify the logic. In the meeting editor we would previously automatically move the end time forward if it was set before the start time, but this didn't play well with the simplified component. Now it will simply show a form validation error (which is how it works in f.ex. the event-editor).~~
Screenshot 2023-06-10 at 09 54 58

The end-time auto-moving is kept intact! It now moved the end time to ~two hours after the start time when blurring (deselecting) the start time field.

# Testing

- [x] I have thoroughly tested my changes.

I've gone through every usage of the component in the webapp, and checked manually that it still works as expected.

### CODE REVIEW

**Review by ivarnakken — APPROVED** [review]
Code looks solid, and the component looks nicer!

But I do like when the end time automatically updates after changing the start time.

**Comment by erlingfn** [comment]
Excellent rewrite, yet the feature moving the end time forward will be sorely missed. Is it not possible to make this work with functional components?

**Review by erlingfn — APPROVED** [review]
Excellent rewrite, yet the feature moving the end time forward will be sorely missed. Is it not possible to make this work with functional components?

**Comment by ivarnakken** [comment]
> Excellent rewrite, yet the feature moving the end time forward will be sorely missed. Is it not possible to make this work with functional components?

I'd like to add that we should extend the date picker to have a range functionality. Like this: https://ui.shadcn.com/docs/components/date-picker#date-range-picker

**Comment by ivarnakken** [comment]
@eikhr What's the status on this? Is see there are some unresolved questions.

**Comment by eikhr** [comment]
> @eikhr What's the status on this? Is see there are some unresolved questions.

Yep, I am going to add back the functionality for automatically moving end date forwards. Just haven't gotten around to it yet.

**Review by ivarnakken — APPROVED** [review]

**Pull request merged**
