### PR TITLE
Make icon on latest readme comp "act" as a button

### PR DESCRIPTION
**Pull request by ivarnakken**
# Description

Although you can click on the entire component to expand it, I think it's good for the icon to "act" (or, look) as a button since the user may assume (s)he should click on it.

Also, this lets the user "tab" to and use the component. So I suppose that's a "yay" for universal design

# Result

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

https://github.com/webkom/lego-webapp/assets/69514187/462ee059-ce03-439b-b6a5-72f6540db8f4

# Testing

- [x] I have thoroughly tested my changes.

See video above

### CODE REVIEW

**Review by itsisak — APPROVED** [review]
I agree, this helps boost accessibility

**Review by norbye — APPROVED** [review]

**Review by eikhr — APPROVED** [review]

**Comment by falbru** [comment]
I'm a bit confused. For me it looks like the video you've provided exactly how it behaves right now. I can also tab to the icon to expand it, so I'm not noticing any difference.

**Comment by ivarnakken** [comment]
> I'm a bit confused. For me it looks like the video you've provided exactly how it behaves right now. I can also tab to the icon to expand it, so I'm not noticing any difference.

The issue is in `master`, which has not been deployed. I assume you only tested in prod?

**Comment by falbru** [comment]
yup hehe. Then it makes sense :)

**Pull request merged**
