### PR TITLE
Update readmeFetching function

### PR DESCRIPTION
**Pull request by odinuge**

### CODE REVIEW

**Comment by SmithPeder** [comment]
Why is this needed?

**Comment by odinuge** [comment]
Readme is slow

**Comment by odinuge** [comment]
Hmm.
Looks like it is way faster now, than last time I was checking. Guess we don't need this then :upside_down_face:

**Comment by odinuge** [comment]
We can still move the `first`-count out from the query, but we can keep the SSR fetching. :smile:

**Pull request merged**
