### PR TITLE
Made the gradelist in ascending order

### PR DESCRIPTION
**Pull request by magnusbrecke**
# Description

Under change classes on profile page the classes weren't presented in ascending order, more like in random order. I sorted the groups presented by id. And now they are in ascending order.

# Result
**Before:**
Skjermbilde 2024-02-20 kl  21 36 58

**After:**
Skjermbilde 2024-02-20 kl  21 44 43

If you've made visual changes, please check the boxes below and include images showing the changes. Descriptions are appreciated.

- [ x] Changes look good on both light and dark theme.
- [ x] Changes look good with different viewports (mobile, tablet, etc.).
- [x ] Changes look good with slower Internet connections.

# Testing

- [ x] I have thoroughly tested my changes.

Please describe what and how the changes have been tested, and provide instructions to reproduce if necessary.

---

Resolves ABA-526

### CODE REVIEW

**Review by Bestem0r — APPROVED** [review]
Very nice! A good addition

**Review by itsisak — APPROVED** [review]
Straight 🔥

**Comment by haukkagu** [comment]
Good job!

**Comment by ivarnakken** [comment]
Awesome!

**Pull request merged**
