### PR TITLE
Improve our use of gray

### PR DESCRIPTION
**Pull request by ivarnakken**
# Description

Our gray color palette has been a mess for a long time. There's far too many shades, and our use of them feels more or less random. leading to pages looking different across the webapp. This standarizes our use of it, while also improving the color. The difference looks minimal, but the reduction in technical debt is major.

Not sure how to show this. As I've said, the visual changes are very minimal, but branch out and check it out for yourself. If the chosen color are not satisfactory, they can now easily be changed later due to everything being variables 🤩 

# Testing

- [x] I have thoroughly tested my changes.

Went through ALL use of "gray" ..

### CODE REVIEW

**Comment by ivarnakken** [comment]
image

That's what I call, sexy.

**Review by haukkagu — APPROVED** [review]
Looks very good! The pills finally look good on dark mode. Personally though, I'd prefer if there was a higher contrast between the pills and the background. The pills doesn't stick out as much as before.

**Comment by LudvigHz** [comment]
The only thing I could find here was the button color. I liked the blue tint we had there. Made them "pop" a bit more and be a bit more vibrant and interesting.

Also, in the administrate tables, the gray here is also more "brown" as the previous was a bit lighter and blueish. Minor preference for the current one.

| before      | after                   |
|---------------|-------------------------|
| image | image |
| image|  image |


Otherwise really nice :ok_hand:.

**Comment by ivarnakken** [comment]
> The only thing I could find here was the button color. I liked the blue tint we had there. Made them "pop" a bit more and be a bit more vibrant and interesting.

I feel like the new buttons look better. Also, they align with our use of gray, which I feel is very important. By getting rid of the "mono" shades, we now have no "blueish" grays, which I thought you preferred?

> Also, in the administrate tables, the gray here is also more "brown" as the previous was a bit lighter and blueish. Minor preference for the current one.

I agree. Making it lighter now.

**Comment by LudvigHz** [comment]
> I feel like the new buttons look better. Also, they align with our use of gray, which I feel is very important. By getting rid of the "mono" shades, we now have no "blueish" grays, which I thought you preferred?

I did think the old ones might have had just a bit too much blue, but the new ones are just a bit too brown as well. Some lighter color wouldn't hurt IMO. This is nitpicking though

**Comment by mattiastofte** [comment]
Looks great! As you've mentioned this cleans up the color palette and standardizes the webapp, making it easier to stay consistent with the design. I also actually prefer the warmer grays. LGTM!

**Comment by ivarnakken** [comment]
> On a sidenote: I think we should look at modernizing the buttons as a whole. Getting som JavaFX vibes.

Yes, they totally need to be iterated on. I added some more border-radius now, and reduced the border color, which kind of helped.

**Comment by ivarnakken** [comment]
@LudvigHz
I made the administrate table and buttons a little less "brown".

**Comment by ivarnakken** [comment]
Like I've said, if we're not happy with the chosen gray colors, they can very easily be changed later. This PR is mostly for standardizing everything and reducing technical debt.

**Review by LudvigHz — APPROVED** [review]
LGTM

**Pull request merged**
