### PR TITLE
Fix loading indicator in email routes

### PR DESCRIPTION
**Pull request by JonasBak**
The admin/email route bugs out after a previous bugfix

### CODE REVIEW

**Comment by orhanhenrik** [comment]
Will this still show a loading indicator when loading more when scrolling to bottom?

**Comment by JonasBak** [comment]
> Will this still show a loading indicator when loading more when scrolling to bottom?

Yes, and it makes the user list and the "lists-list" behave the same, which it doesn't do in prod now

**Comment by JonasBak** [comment]
> Will this still show a loading indicator when loading more when scrolling to bottom?

This is just the initial loading-indicator for the route

**Comment by LudvigHz** [comment]
Shouldn't the loading indicator in the paginator do this as well? I.e having a loading indicator on the route is unnecessary.

**Comment by mrfarstad** [comment]
LGTM 💯

**Pull request merged**
