### PR TITLE
Add no-unused-prop-types and fixed errors

### PR DESCRIPTION
**Pull request by SmithPeder**
The thing we all needed!! ESLint, plz save my flow ❤️ 

screenshot 2019-02-19 at 23 43 08

### CODE REVIEW

**Comment by SmithPeder** [comment]
@JonasBak Now you can use ALE! 👍  We did not have unused prop-types as a rule in ESLint

**Comment by JonasBak** [comment]
`// $FlowFixMe` :sunglasses:

**Comment by odinuge** [comment]
Fiks denne istedenfor @SmithPeder :100:

**Comment by SmithPeder** [comment]
byby 👎

**Pull request closed without merging**
