### PR TITLE
Fix Italic issue

### PR DESCRIPTION
**Pull request by ShaileshS1702**
# Description

Fixed the italic issue on landingpage. fixed issue were "Datateknologi was written normally, but "Cybersikkerhet og datakommunikasjon" were written in italics.
**bug-fix**

# Result

 **before** 
image

 **after**
image

# Testing

- [ ] I have thoroughly tested my changes.
I've tested for different sizes: Issue
image

It may be difficult to differentiate which to words do correspond to one thing. It may also look like it's one study programme or three
---

Resolves ... (either GitHub issue or Linear task)
ABA-631

### CODE REVIEW

**Review by ivarnakken — APPROVED** [review]
Thanks!

**Review by danielyanghansen — APPROVED** [review]
Nice! Just remember to run `yarn prettier`

**Comment by ivarnakken** [comment]
Our linter, [`prettier`](https://github.com/prettier/prettier), is saying your code needs to be reformatted. No worries!

You can fix this with the command `yarn prettier`. This is one of many "scripts" we have configured for this project, which you can view in the `package.json` file under "scripts". I recommend adding `prettier` as an extension to your code editor though - makes life a whole lot easier.

After the fix, you can stage it (`git add .`) and add it to your previous commit by typing `git commit --amend`. You may also add a `--no-edit` flag since you don't need to edit the commit message: `git commit --amend --no-edit`.
After this you'll have to force push your changes. `git push --force` or `git push -f` (same thing).

**Review by haukkagu — APPROVED** [review]
Great job!

**Comment by ivarnakken** [comment]
@ShaileshS1702 
Seems you added a revert commit. It doesn't seem to do anything here, and we can just squash this PR and be done for the day, but if you want to remove it you can do; 
1. `git rebase -i HEAD~1`
2. Change `pick` to `drop` on the revert commit
3. Force push to this remote branch like described above

The `-i` in `git rebase` means the rebase is "interactive", which let's you do a bunch of cool stuff.

**Pull request merged**
