### PR TITLE
Banner

### PR DESCRIPTION
**Pull request by ShaileshS1702**
# Description

With "kommunikasjonsteknologi og cybersikkerhet"'s newest name change the banner had to be updated,
# Result

If you've made visual changes, please include **before** and **after** images, preferably with a description. Make sure they do not contain any real user information.

1f05e281e23936a0dfc8
m/webkom/lego-webapp/assets/102583541/b90066bd-6669-4d53-af3f-9a139d2629d3)

# Testing

- [x] I have thoroughly tested my changes.

I ran lego-webapp in staging and it looked good.

---

Resolves ... (either GitHub issue or Linear task)

### CODE REVIEW

**Review by ivarnakken — APPROVED** [review]

**Comment by ivarnakken** [comment]
Why is only the dark mode version transparent 🙃

**Review by magnusbrecke — COMMENTED** [review]
Should the picture size of the added picture be of the same dimensions as the deleted ones?

**Comment by ShaileshS1702** [comment]
> Why is only the dark mode version transparent 🙃

The old ones was like that and thought we should do anything

**Comment by ivarnakken** [comment]
Remember to fill out everything in the pull request description
image

**Review by magnusbrecke — APPROVED** [review]
It looks good

**Pull request merged**
