### PR TITLE
Add revybanner

### PR DESCRIPTION
**Pull request by jennymul**
# Description

Add banner to promote Abakusrevyen.

# Result
Screenshot from 2024-02-15 19-51-29

If you've made visual changes, please check the boxes below and include images showing the changes. Descriptions are appreciated.

- [X] Changes look good on both light and dark theme.
- [X] Changes look good with different viewports (mobile, tablet, etc.).
- [X] Changes look good with slower Internet connections.

> [!CAUTION]
> Make sure your images do not contain any real user information.

<table>
    <tr>
        <td width="25%">Description</td>
        <td>Before</td>
        <td>After</td>
    </tr>
    <tr>
        <td>
            ...
        </td>
        <td>
            ...
        </td>
        <td>
            ...
        </td>
    </tr>
</table>

# Testing

- [X] I have thoroughly tested my changes.

Please describe what and how the changes have been tested, and provide instructions to reproduce if necessary.

---

Resolves ... (either GitHub issue or Linear task)

### CODE REVIEW

**Review by dobif — APPROVED** [review]
LGTM!

**Review by itsisak — APPROVED** [review]
🔥🔥🔥

**Review by Bestem0r — APPROVED** [review]
Nice! 🚀

**Review by ivarnakken — COMMENTED** [review]
Remember to also update the banner when you are not logged in. I know it's dumb but we have two different ones he he

**Review by haukkagu — APPROVED** [review]
Good job!

**Review by ivarnakken — APPROVED** [review]

**Pull request merged**
