### PR TITLE
Move Card, Icon and Layout components into lego-bricks

### PR DESCRIPTION
**Pull request by ivarnakken**
# Description

I initially only needed the card component, but since that uses the layout and icon component I had to add those as well. 

# Result

No visual changes.

# Testing

- [x] I have thoroughly tested my changes.

All components still work.

### CODE REVIEW

**Review by eikhr — APPROVED** [review]
Great work! Definitely some of the most important components💯

I would love some storybook stories though:)

**Comment by ivarnakken** [comment]
> I would love some storybook stories though:)

heh that was in my todos. I'll get it in before merging

**Review by danielyanghansen — APPROVED** [review]
Looks good to me.
I assume the linter is already complaining about the import order some places 🙃

**Comment by ivarnakken** [comment]
> I assume the linter is already complaining about the import order some places 🙃

What do you mean? Nothing wrong with the import order here

**Pull request merged**
