### PR TITLE
Fix aspect ratio in gallery images

### PR DESCRIPTION
**Pull request by theodorsm**
https://github.com/webkom/lego/issues/1821
Before:
format
After:
format_fix

### CODE REVIEW

**Comment by LudvigHz** [comment]
:100: Maybe have the background not black?

**Comment by SmithPeder** [comment]
What color is better than black? Transparent will look wired, won't it?

**Comment by theodorsm** [comment]
> What color is better than black? Transparent will look wired, won't it?

I think this looks a bit cleaner. Don't you agree? 

gallery_white

**Comment by SmithPeder** [comment]
Hmmm, I feel like that IMG is an "outcast". Most gallery images fit quite nicely, and generally, the images are quite dark. Example https://abakus.no/photos/385/picture/25146

I feel like a white background on this img would be wired.

Screenshot 2020-03-22 at 18 40 34

**Comment by theodorsm** [comment]
I fell this side-by-side comparison illustrates that even though the picture is dark, a white backround still looks clean. 

Screenshot_20200322_184605

**Comment by SmithPeder** [comment]
Ahh, okay I agree, it still looks clean. I approve

**Pull request merged**
