### PR TITLE
Change language and casing on user settings

### PR DESCRIPTION
**Pull request by tirilsys**

### CODE REVIEW

**Review by SmithPeder — APPROVED** [review]
Good work!!!!!!

**Review by LudvigHz — APPROVED** [review]
:rocket:

**Comment by SmithPeder** [comment]
@tirilsys There are some E2E test cases that look for these strings when navigating the page 😢 

Here the string "Change password" is hard-coded
https://github.com/webkom/lego-webapp/blob/master/cypress/integration/password_change_spec.js

Here the string "Submit" is hard-coded
https://github.com/webkom/lego-webapp/blob/master/cypress/integration/profile_spec.js#L123

**Review by SmithPeder — CHANGES_REQUESTED** [review]
Fix `E2E cypress` tests, then we can merge 👍🏻

**Comment by LudvigHz** [comment]
This now targets the heading, since it contains "Endre passord" as well as the button.
We need to change the selector used to get the button element i cypress for this test to be fixed.

**Pull request closed without merging**
