### PR TITLE
Fix login bugs

### PR DESCRIPTION
**Pull request by odinuge**
This fixes login bug when HTTPError is rendered, and the bug when
navigation between 404 pages that doesn't have a router entry. It also
clears the fetchHistory on login.

### CODE REVIEW

**Comment by odinuge** [comment]
Aaand, what does people think about having `replaceUnlessLoggein` on `/events/pk`. Have heard a lot of complains about it.. This atleast allows the user to login when having a 404 before login. :smile:

**Comment by odinuge** [comment]
This will also fix the strange `undefined` is not a function from the `PhantomJS` browser:

https://sentry.abakus.no/webkom/lego-webapp/issues/3908/

**Comment by ekmartin** [comment]
yeah, that sounds like a good temporary measure (until we've sorted out the permission stuff for events)

**Comment by odinuge** [comment]
Smooth. Will add that too

**Pull request merged**
