### PR TITLE
Hide banner

### PR DESCRIPTION
**Pull request by Bestem0r**
# Description

Hide the banner since "opptaksperioden" is over.

# Result

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

# Testing

- [x] I have thoroughly tested my changes.

Navigate to the front page and verify that the banner is hidden.

### CODE REVIEW

**Comment by norbye** [comment]
Ey Ey Ey, revue is still recruiting

So if you want to change it, maybe rather change it to Abakusrevyen instead of Abakus

**Comment by Bestem0r** [comment]
> Ey Ey Ey, revue is still recruiting
> 
> So if you want to change it, maybe rather change it to Abakusrevyen instead of Abakus

Whoops, completely forgot about that 😅! Consider this PR on hold then...

**Comment by norbye** [comment]
> > Ey Ey Ey, revue is still recruiting
> > So if you want to change it, maybe rather change it to Abakusrevyen instead of Abakus
> 
> Whoops, completely forgot about that 😅! Consider this PR on hold then...

image

**Comment by ivarnakken** [comment]
@Bestem0r Perhaps prepare this for merge and deployment soon? 😄

**Review by ivarnakken — APPROVED** [review]

**Review by norbye — APPROVED** [review]
Admissions end tonight, so deploying any time after midnight is gucci 

Remember to squash merge this one

**Comment by Bestem0r** [comment]
Hmm.. Looks like CI is broken. Rerunning previously good builds now fail. I merged this since it should be good in theory, but cannot deploy yet. Do you have any idea on how to fix CI? @ivarnakken @norbye

**Comment by norbye** [comment]
> Hmm.. Looks like CI is broken. Rerunning previously good builds now fail. I merged this since it should be good in theory, but cannot deploy yet. Do you have any idea on how to fix CI? @ivarnakken @norbye

We're having some cache issues it seems.. I cleared the cache on CI and now it seems to run smoothly

**Pull request merged**
