### PR TITLE
Correct flex direction on content in brand page (#3674)

### PR DESCRIPTION
**Pull request by TobiasBorning**
# Description
Defined flex direction by using the column property of the Flex component. Previously defined in the corresponding stylesheet, which gets overwritten by the column property of the Flex component.

# Result

-  ✔️ Changes look good on both light and dark theme.
-  ✔️ Changes look good with different viewports (mobile, tablet, etc.).
-  ✔️ Changes look good with slower Internet connections.

<table>
    <tr>
        <td width="25%">Description</td>
        <td>Before</td>
        <td>After</td>
    </tr>
    <tr>
        <td>
          Fix
        </td>
        <td>
  image
        </td>
        <td>
            image
        </td>
    </tr>
</table>

# Testing

- ✔ I have thoroughly tested my changes.
### Works both client and server side.
---

Resolves webkom/lego#3674

### CODE REVIEW

**Review by ivarnakken — APPROVED** [review]
Awesome 😍 😍 🎉

**Review by eikhr — APPROVED** [review]
Thanks!

**Review by falbru — APPROVED** [review]
Great work!

**Comment by ivarnakken** [comment]
Ran this through our CI now - worked like a charm! 🥳

**Pull request merged**
