### PR TITLE
Fix interest group logo height on details page

### PR DESCRIPTION
**Pull request by olekvin**

### CODE REVIEW

**Comment by SmithPeder** [comment]
Do you have some screenshots of the improvement? 

If I apply this change inline on the `.logo` class I get the following, so I feel like it maybe makes it worse?

**From**
image

**To**
image

**Comment by olekvin** [comment]
If it doesn't work on you I have to look at it again. I noticed the issue for the new "Habanero" interest group, which got fixed by this.

**Comment by olekvin** [comment]
Should now look better on all screen sizes:
Pre PR:
image
Post PR: 📸 
image

**Comment by olekvin** [comment]
What do you think, @SmithPeder?

**Comment by LudvigHz** [comment]
Checked this out, and indeed it's more round. Nice job!

**Review by SmithPeder — APPROVED** [review]
LGTM

**Pull request merged**
